name: Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:

  php:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.0', '8.1']

    env:
      SYMFONY_ARGS: --no-tls
      COMPOSER_ARGS: --prefer-dist
      DOCKER_INTERACTIVE_ARGS: -t

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: gd, intl, json

      - name: Set project php-version
        run: |
          echo "${{ matrix.php }}" > .php-version

      - name: Install symfony CLI
        run: |
          curl https://get.symfony.com/cli/installer | bash
          echo "${HOME}/.symfony5/bin" >> $GITHUB_PATH

      - uses: actions/cache@v1
        id: cache-composer
        with:
          path: /home/runner/.composer/cache
          key: composer2-php:${{ matrix.php }}-${{ github.sha }}
          restore-keys: composer2-php:${{ matrix.php }}-

      - run: mkdir -p /home/runner/{.composer/cache,.config/composer}
        if: steps.cache-composer.outputs.cache-hit != 'true'

      - name: Composer v2
        run: sudo composer self-update --2

      - name: Composer Github Auth
        run: composer config -g github-oauth.github.com ${{ github.token }}

      - run: make install

      - run: make test.composer

      - run: make test.phpcs

      - run: make test.phpunit

      - run: make test.phpstan

      - run: make test.phpmd

      - run: make test.phpspec

      - run: make test.yaml

      - run: make test.twig

      - run: make test.schema

      - run: make test.container
